# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/dfs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/dfs.proto\"H\n\x0c\x42lockRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\t\x12\x15\n\rreplica_nodes\x18\x03 \x03(\t\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x11\x42lockDataResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9e\x01\n\x0f\x44\x61taNodeService\x12+\n\nStoreBlock\x12\r.BlockRequest\x1a\x0e.StoreResponse\x12/\n\x0eReplicateBlock\x12\r.BlockRequest\x1a\x0e.StoreResponse\x12-\n\x08GetBlock\x12\r.BlockRequest\x1a\x12.BlockDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKREQUEST']._serialized_start=20
  _globals['_BLOCKREQUEST']._serialized_end=92
  _globals['_STORERESPONSE']._serialized_start=94
  _globals['_STORERESPONSE']._serialized_end=143
  _globals['_BLOCKDATARESPONSE']._serialized_start=145
  _globals['_BLOCKDATARESPONSE']._serialized_end=215
  _globals['_DATANODESERVICE']._serialized_start=218
  _globals['_DATANODESERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
